freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  name: FreeBSD test
  install_script: pkg update -f && pkg install -y augeas pkgconf tcl86
  test_script: ./configure --with-tcl=/usr/local/lib/tcl8.6 && make test
